version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_USERS_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  service-utilisateurs:
    build:
      context: ./service-utilisateurs
    container_name: service-utilisateurs
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_USERS_NAME}
      JWT_SECRET: ${JWT_SECRET_USERS}
      DATABASE_URL: ${DATABASE_URL_USERS}

  postgres-produits:
    image: postgres:15
    container_name: postgres-produits
    environment:
      POSTGRES_DB: ${DB_PRODUCTS_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-produits:/var/lib/postgresql/data

  service-produits:
    build:
      context: ./service-produits
    container_name: service-produits
    depends_on:
      - postgres-produits
    ports:
      - "3001:3000"
    environment:
      DB_HOST: postgres-produits
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_PRODUCTS_NAME}
      JWT_SECRET: ${JWT_SECRET_PRODUCTS}
      DATABASE_URL: ${DATABASE_URL_PRODUCTS}

  frontend:
    build:
      context: ./quickserve-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: quickserve-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:80"
    depends_on:
      - service-utilisateurs

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8080:80"
    depends_on:
      - service-utilisateurs
      - service-produits

volumes:
  pgdata:
  pgdata-produits:
