version: "3.8"

services:
  service-utilisateurs:
    build: ./service-utilisateurs
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-utilisateurs:5432/utilisateurs
    depends_on:
      - postgres-utilisateurs

  postgres-utilisateurs:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: utilisateurs
    ports:
      - "5433:5432"
    volumes:
      - postgres_utilisateurs_data:/var/lib/postgresql/data

  service-produits:
    build: ./service-produits
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-produits:5432/produits
    depends_on:
      - postgres-produits

  postgres-produits:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produits
    ports:
      - "5434:5432"
    volumes:
      - postgres_produits_data:/var/lib/postgresql/data

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-utilisateurs
      - service-produits

volumes:
  postgres_utilisateurs_data:
  postgres_produits_data:
